---
- hosts: all
  accelerate: false
  sudo: yes
  gather_facts: false
  vars_files:
      - vars_common.yml

  tasks:
      - name: install core system, networking, and python packages
        apt: pkg={{ item }} update_cache=yes state=present
        with_items: system_packages

      - name: install python system packages
        easy_install: name={{item}}
        with_items: python_packages

     # - name: add repository
     #   apt_repository: repo='ppa:gwendal-lebihan-dev/cinnamon-stable'

     # - name: update repositories
     #   command: /usr/bin/apt-get update

      - name: Desktop Install
        apt: pkg={{ item }} update_cache=yes state=present
        with_items: desktop_packages

      - name: Remove Unity Desktop
        apt: pkg={{ item }} update_cache=yes state=absent
        with_items: unity_packages

      # start GDM for logins
      - service: name=lightdm state=started

      # ansible cannot be easy_install'ed
      - name: install ansible
        pip: name=ansible

      #
      # setup development flyscript directories and templates
      #
      - name: flyscript root directory
        file: path={{ project_root_stage }}
            state=directory mode=775
            owner={{ project_owner_stage }} group={{ project_group_stage }}

      - name: flyscript portal directory
        file: path={{ project_root_stage }}/{{ project_name }}
            state=directory mode=775
            owner={{ project_owner_stage }} group={{ project_group_stage }}
        register: portal_dir_result

      - name: flyscript tools directory
        file: path=/flyscript/tools
            state=directory mode=775
            owner=root group=root

      #
      # setup deployment flyscript directories
      #
      - name: flyscript wsgi directory
        file: path={{ project_root_deploy }}/wsgi
            state=directory mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: flyscript home directory
        file: path={{ project_root_deploy }}/.flyscript
            state=directory mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      #
      # setup GNOME environment
      #
      - name: portal management scripts
        file: path={{ project_root_deploy }}/bin
            state=directory mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User exec items
        template: src=templates/portal_script.sh
            dest={{ project_root_deploy }}/bin/portal_script.sh
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User exec items
        template: src=templates/startDR.sh
            dest={{ project_root_deploy }}/bin/startDR.sh
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
      - name: User exec items
        template: src=templates/startFX.sh
            dest={{ project_root_deploy }}/bin/startFX.sh
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}


      - name: portal management GUI config
        file: path={{ project_root_deploy }}/.local/share/applications
            state=directory mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
      
      - name: user autostart
        file: path={{ project_root_deploy }}/.config/autostart
            state=directory mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
 
      - name: User menu items
        template: src=templates/alacarte-made.desktop
            dest={{ project_root_deploy }}/.local/share/applications/alacarte-made.desktop
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User menu items
        template: src=templates/alacarte-made-1.desktop
            dest={{ project_root_deploy }}/.local/share/applications/alacarte-made-1.desktop
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User menu items
        template: src=templates/alacarte-made-2.desktop
            dest={{ project_root_deploy }}/.local/share/applications/alacarte-made-2.desktop
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User menu items
        template: src=templates/startDR.sh.desktop
            dest={{ project_root_deploy }}/.config/autostart/StartDR.sh.desktop
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}

      - name: User menu items
        template: src=templates/startFX.sh.desktop
            dest={{ project_root_deploy }}/.config/autostart/startFX.sh.desktop
            mode=775
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
                        


      #
      # setup enviroment for aliases, helper functions, and ipython notebooks
      #
      - name: flyscript helper functions and aliases
        template: src=templates/vm_env.sh
            dest={{ project_root_stage }}/tools/vm_env.sh
            mode=775
            owner=root group=root

      - name: update bashrc to source vm_env.sh
        lineinfile:
            dest=/home/vagrant/.bashrc
            line="source {{ project_root_stage }}/tools/vm_env.sh"
            regexp="^source {{ project_root_stage }}/tools/vm_env.sh"
            insertafter=EOF
            state=present

      - name: ipython notebook folder
        file: path=/home/vagrant/ipython_notebooks
            state=directory mode=775
            owner=vagrant group=vagrant

      #
      # setup apache config
      #
      - name: flyscript site template
        template: src=templates/flyscript_portal_site.j2
            dest=/etc/apache2/sites-available/flyscript_portal
            mode=664
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
        notify:
        - restart apache

      - name: enable flyscript site
        file: path=/etc/apache2/sites-enabled/001-flyscript_portal
            src=/etc/apache2/sites-available/flyscript_portal
            state=link
            mode=664
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
        notify:
        - restart apache

      - name: disable default site
        file: path=/etc/apache2/sites-enabled/000-default state=absent

      - name: install portal wsgi configuration
        template: src=templates/flyscript_portal.wsgi
            dest={{ project_root_deploy }}/wsgi/flyscript_portal.wsgi
            mode=664
            owner={{ project_owner_deploy }} group={{ project_group_deploy }}
        notify:
        - restart apache

      - meta: flush_handlers

  handlers:
      - include: handlers.yml

- include: stage.yml
- include: deploy.yml
