---
- name: PULL FROM GITHUB TO STAGING AREA
  hosts: all
  accelerate: false
  sudo: yes
  gather_facts: false
  vars_files:
      - vars_common.yml
  vars:
    project_root: "{{ project_root_stage }}"
    project_name: "{{ project_name }}"
    project_repo: "{{ project_repo_stage }}"
    project_owner: "{{ project_owner_stage }}"
    project_group: "{{ project_group_stage }}"
    virtualenv: "{{ virtualenv_stage }}"
    force_checkout: no

  tasks:
      - name: portal github checkout
        git: repo={{ project_repo }}
           dest={{ project_root }}/{{ project_name }}
           update=yes
           force={{ force_checkout }}
        notify:
        - portal static directory
        - update virtualenv
        - portal syncdb
        - portal static files
        - clear pyc files
        - portal reload
        - ensure correct directory ownership
        - restart apache

      - meta: flush_handlers

  handlers: 
      - include: handlers.yml
